In [1]:
import pandas as pd 
import numpy as np

In [3]:
df=pd.read_csv('surat_uncleaned.csv')
df.head(4)

,property_name,areaWithType,square_feet,transaction,status,floor,furnishing,facing,description,price_per_sqft,price
0,2 BHK Apartment for Sale in Dindoli Surat,Carpet Area,644 sqft,New Property,Poss. by Oct '24,5 out of 10,Unfurnished,West,"Luxury project with basement parking, Solar ro...","₹2,891 per sqft",₹33.8 Lac
1,2 BHK Apartment for Sale in Althan Surat,Super Area,1278 sqft,New Property,Poss. by Jan '26,6 out of 14,Unfurnished,South -West,2 And 3 BHK Luxurious Flat for Sell In New Alt...,"₹3,551 per sqft",₹45.4 Lac
2,2 BHK Apartment for Sale in Pal Gam Surat,Super Area,1173 sqft,Resale,Ready to Move,5 out of 13,Semi-Furnished,East,This affordable 2 BHK flat is situated along a...,"₹3,800 per sqft",₹44.6 Lac
3,2 BHK Apartment for Sale in Jahangirabad Surat,Carpet Area,700 sqft,New Property,Ready to Move,6 out of 14,Unfurnished,East,2 BHK Flat For sell IN Jahangirabad Prime Loca...,"₹3,966 per sqft",₹47 Lac

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4525 entries, 0 to 4524
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   property_name   4525 non-null   str
 1   areaWithType    4525 non-null   str
 2   square_feet     4525 non-null   str
 3   transaction     4421 non-null   str
 4   status          4524 non-null   str
 5   floor           4480 non-null   str
 6   furnishing      4185 non-null   str
 7   facing          3936 non-null   str
 8   description     3154 non-null   str
 9   price_per_sqft  4157 non-null   str
 10  price           4525 non-null   str
dtypes: str(11)
memory usage: 1.6 MB

In [5]:
df.isnull().sum()

property_name        0
areaWithType         0
square_feet          0
transaction        104
status               1
floor               45
furnishing         340
facing             589
description       1371
price_per_sqft     368
price                0
dtype: int64

In [6]:
df=df.drop_duplicates()

In [7]:
df

,property_name,areaWithType,square_feet,transaction,status,floor,furnishing,facing,description,price_per_sqft,price
0,2 BHK Apartment for Sale in Dindoli Surat,Carpet Area,644 sqft,New Property,Poss. by Oct '24,5 out of 10,Unfurnished,West,"Luxury project with basement parking, Solar ro...","₹2,891 per sqft",₹33.8 Lac
1,2 BHK Apartment for Sale in Althan Surat,Super Area,1278 sqft,New Property,Poss. by Jan '26,6 out of 14,Unfurnished,South -West,2 And 3 BHK Luxurious Flat for Sell In New Alt...,"₹3,551 per sqft",₹45.4 Lac
2,2 BHK Apartment for Sale in Pal Gam Surat,Super Area,1173 sqft,Resale,Ready to Move,5 out of 13,Semi-Furnished,East,This affordable 2 BHK flat is situated along a...,"₹3,800 per sqft",₹44.6 Lac
3,2 BHK Apartment for Sale in Jahangirabad Surat,Carpet Area,700 sqft,New Property,Ready to Move,6 out of 14,Unfurnished,East,2 BHK Flat For sell IN Jahangirabad Prime Loca...,"₹3,966 per sqft",₹47 Lac
4,"2 BHK Apartment for Sale in Orchid Fantasia, P...",Super Area,1250 sqft,Orchid Fantasia,New Property,Unfurnished,2,2,"Multistorey Apartment for Sale in Palanpur, Su...","₹3,600 per sqft",₹45 Lac
...,...,...,...,...,...,...,...,...,...,...,...
4520,6 BHK Apartment for Sale in Millionaires Lifes...,Carpet Area,2000 sqft,New Property,Poss. by Dec '26,5 out of 12,Unfurnished,South - East,"Check out Millionaires Lifestyle in Vesu, one ...",NaN,Call for Price
4521,"4 BHK Apartment for Sale in Savan Superia, Alt...",Super Area,3600 sqft,New Property,Poss. by Dec '25,5 out of 16,Unfurnished,South - East,Superia is a premium residential project launc...,NaN,Call for Price
4522,5 BHK Apartment for Sale in Roongta Green Vall...,Carpet Area,2250 sqft,New Property,Poss. by Dec '25,7 out of 13,Unfurnished,North - East,"When it comes to beautiful homes, nothing beat...",NaN,Call for Price
4523,"6 BHK Apartment for Sale in Cellestial Dreams,...",Carpet Area,3450 sqft,New Property,Ready to Move,7 out of 18,Unfurnished,North - West,"DRB Ravani Cellestial Dreams in Vesu, Surat is...",NaN,Call for Price
4524,4 BHK Apartment for Sale in Roongta Green Vall...,Super Area,4500 sqft,New Property,Ready to Move,3 out of 12,Unfurnished,North,Roongta Green Valley is one of the popular res...,NaN,Call for Price

In [8]:
df['square_feet'].unique()

<ArrowStringArray>
[ '644 sqft', '1278 sqft', '1173 sqft',  '700 sqft', '1250 sqft', '1265 sqft',
 '1404 sqft', '1180 sqft',  '720 sqft',  '748 sqft',
 ...
 '2824 sqft', '4730 sqft', '2881 sqft', '3945 sqft', '2282 sqft', '4580 sqft',
 '2970 sqft', '2545 sqft', '5175 sqft', '2620 sqft']
Length: 1399, dtype: str

In [9]:
df['square_feet']=df['square_feet'].str.split(" ").str[0]

In [10]:
df['square_feet']=pd.to_numeric(df['square_feet'],errors='coerce')

In [11]:
df['price_per_sqft'].unique()

<ArrowStringArray>
['₹2,891 per sqft ', '₹3,551 per sqft ', '₹3,800 per sqft ',
 '₹3,966 per sqft ', '₹3,600 per sqft ', '₹3,411 per sqft ',
                nan, '₹3,392 per sqft ', '₹3,751 per sqft ',
 '₹3,200 per sqft ',
 ...
 '₹5,487 per sqft ', '₹7,300 per sqft ', '₹6,040 per sqft ',
 '₹6,811 per sqft ', '₹5,930 per sqft ', '₹7,470 per sqft ',
 '₹8,018 per sqft ', '₹8,512 per sqft ', '₹8,200 per sqft ',
 '₹5,756 per sqft ']
Length: 2135, dtype: str

In [12]:
(df['price_per_sqft'].isna().sum()/len(df))*100

np.float64(8.106884057971014)

In [13]:
df[df['transaction']=='New Property'].isna().sum()

property_name       0
areaWithType        0
square_feet         3
transaction         0
status              0
floor               0
furnishing          4
facing             25
description       198
price_per_sqft     34
price               0
dtype: int64

In [14]:
df=df.dropna(subset=['price_per_sqft'])

In [15]:
df['price_per_sqft']=df['price_per_sqft'].str.split(" ").str[0].str.replace("₹","").str.replace(',','').astype(int)

In [16]:
df['price']=df['price_per_sqft']*df['square_feet']

In [17]:
df.sample(5)

,property_name,areaWithType,square_feet,transaction,status,floor,furnishing,facing,description,price_per_sqft,price
2315,"3 BHK Apartment for Sale in Times Luxuria, Ves...",Carpet Area,1179.0,Resale,Ready to Move,11 out of 12,Unfurnished,East,Ready to move 3BHK apartment with all modern a...,4620,5446980.0
1875,3 BHK Apartment for Sale in Adajan Surat,Super Area,1500.0,Resale,Ready to Move,5 out of 11,Furnished,3,NaN,5867,8800500.0
2608,"3 BHK Apartment for Sale in Nakshatra Galaxia,...",Carpet Area,1250.0,Resale,Ready to Move,9 out of 15,Semi-Furnished,South -West,No gst No extra charge in Registrations,3743,4678750.0
4236,"4 BHK Apartment for Sale in Rajhans Cremona, V...",Super Area,4100.0,New Property,Ready to Move,5 out of 14,Unfurnished,West,vesu main road near gd cancal road vesu,6600,27060000.0
1583,4 BHK House for Sale in Amroli Surat,Super Area,1950.0,Resale,Ready to Move,Ground out of 3,Unfurnished,4,"4 BHK, Residential House is available for Sale...",3487,6799650.0

In [18]:
df['areaWithType'].unique()

<ArrowStringArray>
['Carpet Area', 'Super Area', 'Plot Area', 'Built Area']
Length: 4, dtype: str

In [19]:
df['areaWithType']=df['areaWithType'].str.split(" ").str[0]

In [20]:
df['transaction'].unique()

<ArrowStringArray>
[                'New Property',                       'Resale',
              'Orchid Fantasia',                  'Unfurnished',
              'Orchid Gardenia',                        'Congo',
                    'Furnished',                            nan,
       'Main Road, Garden/Park',               'Semi-Furnished',
                            '3',                            '4',
                          'Yes',                           'No',
                            '1',                'Mahavir Nagar',
                    '3 Covered',             'Shagun Residency',
                            '2',                    'Main Road',
                         '10 m',               'Soham Elegance',
                  'Garden/Park',            'Aakash Echo Point',
           'Sundaram Residency',                            '5',
              'Jolly Residency',             'Mangalam Heights',
                   'Green City', 'Pool, Garden/Park, Main Road',
                            '6',         'Co-operative Society',
           'Vatsalya Bungalows',                  '20 Covered,',
         'Raghuvir Silverstone',                          '8 m',
                  'Casa Rivera']
Length: 37, dtype: str

In [21]:
valid=['Resale','New Property']
df=df[df['transaction'].isin(valid)]

In [22]:
df

,property_name,areaWithType,square_feet,transaction,status,floor,furnishing,facing,description,price_per_sqft,price
0,2 BHK Apartment for Sale in Dindoli Surat,Carpet,644.0,New Property,Poss. by Oct '24,5 out of 10,Unfurnished,West,"Luxury project with basement parking, Solar ro...",2891,1861804.0
1,2 BHK Apartment for Sale in Althan Surat,Super,1278.0,New Property,Poss. by Jan '26,6 out of 14,Unfurnished,South -West,2 And 3 BHK Luxurious Flat for Sell In New Alt...,3551,4538178.0
2,2 BHK Apartment for Sale in Pal Gam Surat,Super,1173.0,Resale,Ready to Move,5 out of 13,Semi-Furnished,East,This affordable 2 BHK flat is situated along a...,3800,4457400.0
3,2 BHK Apartment for Sale in Jahangirabad Surat,Carpet,700.0,New Property,Ready to Move,6 out of 14,Unfurnished,East,2 BHK Flat For sell IN Jahangirabad Prime Loca...,3966,2776200.0
7,Office Space for Sale in Vesu Surat,Carpet,700.0,New Property,Poss. by Sep '25,7 out of 10,1,NaN,"best commercial for business ,investors ,busin...",3392,2374400.0
...,...,...,...,...,...,...,...,...,...,...,...
4513,"4 BHK Apartment for Sale in Sangini Siddhanta,...",Super,4000.0,New Property,Ready to Move,5 out of 12,Unfurnished,East,Looking for a 4 bhk property for sale in surat...,8000,32000000.0
4514,4 BHK Apartment for Sale in Millionaires Lifes...,Super,3500.0,New Property,Poss. by Dec '26,5 out of 12,Unfurnished,East,he beautifully designed granite flooring enhan...,6500,22750000.0
4515,"4 BHK Apartment for Sale in Happy Astoria, Ves...",Super,3000.0,New Property,Poss. by Nov '28,5 out of 12,Unfurnished,East,Looking for a 4 bhk property for sale in surat...,6200,18600000.0
4516,"3 BHK Apartment for Sale in Samprati Palace, V...",Super,2620.0,Resale,Ready to Move,5 out of 12,Unfurnished,East,The beautifully designed granite flooring enha...,6031,15801220.0
4517,"4 BHK Apartment for Sale in Samprati Palace, V...",Super,3400.0,Resale,Ready to Move,5 out of 12,Unfurnished,South,Looking for a 4 bhk property for sale in surat...,6000,20400000.0

In [23]:
df['status'].unique()

<ArrowStringArray>
['Poss. by Oct '24', 'Poss. by Jan '26',    'Ready to Move',
 'Poss. by Sep '25', 'Poss. by Dec '25', 'Poss. by Feb '26',
 'Poss. by Dec '26', 'Poss. by Apr '25', 'Poss. by Jan '25',
        '21 X 50.2', 'Poss. by Dec '24', 'Poss. by Aug '25',
 'Poss. by Jul '24', 'Poss. by Feb '25',        '120 X 105',
 'Poss. by May '26',          '36 X 15',      '52.5 X 32.1',
       '12 X 35.92',        '7.29 X 14',        '16.4 X 60',
       '9.42 X 126',          '25 X 12', 'Poss. by Jun '24',
          '21 X 57', 'Poss. by Jul '25', 'Poss. by May '25',
 'Poss. by Mar '26', 'Poss. by Jun '26',      '26.7 X 55.6',
 'Poss. by Jun '25', 'Poss. by Mar '25',          '41 X 20',
 'Poss. by Apr '26', 'Poss. by Nov '24',          '36 X 21',
      '19.2 X 54.8', 'Poss. by Aug '24',      '26.7 X 54.9',
          '38 X 21',         '135 X 75',          '38 X 20',
          '20 X 40',         '114 X 60',          '40 X 21',
 'Poss. by Sep '24', 'Poss. by Nov '25',          '37 X 26',
       '180 X 22.5',         '285 X 51', 'Poss. by Oct '25',
          '37 X 20', 'Poss. by Dec '28',          '48 X 14',
     '45.5 X 21.56',         '60 X 120', 'Poss. by Sep '26',
        '4.55 X 20', 'Poss. by Dec '27', 'Poss. by Oct '26',
          '40 X 20',          '92 X 12',        '39.6 X 20',
         '120 X 60',         '138 X 63',         '120 X 63',
         '126 X 66', 'Poss. by Apr '27', 'Poss. by May '27',
          '55 X 22',         '180 X 45',          '31 X 41',
 'Poss. by Jan '27', 'Poss. by Mar '27',       '46 X 46.17',
 'Poss. by Jul '26',      '110 X 27.27', 'Poss. by Aug '26',
      '73.7 X 53.1', 'Poss. by Jul '27', 'Poss. by Jun '27',
 'Poss. by Nov '26',        '240 X 180', 'Poss. by Mar '28',
         '1200 X 3',        '144 X 105', 'Poss. by Nov '28']
Length: 87, dtype: str

In [24]:
valid = ( df['status'].str.contains(r"Ready|Poss\."))

In [25]:
df=df[valid]

In [26]:
df

,property_name,areaWithType,square_feet,transaction,status,floor,furnishing,facing,description,price_per_sqft,price
0,2 BHK Apartment for Sale in Dindoli Surat,Carpet,644.0,New Property,Poss. by Oct '24,5 out of 10,Unfurnished,West,"Luxury project with basement parking, Solar ro...",2891,1861804.0
1,2 BHK Apartment for Sale in Althan Surat,Super,1278.0,New Property,Poss. by Jan '26,6 out of 14,Unfurnished,South -West,2 And 3 BHK Luxurious Flat for Sell In New Alt...,3551,4538178.0
2,2 BHK Apartment for Sale in Pal Gam Surat,Super,1173.0,Resale,Ready to Move,5 out of 13,Semi-Furnished,East,This affordable 2 BHK flat is situated along a...,3800,4457400.0
3,2 BHK Apartment for Sale in Jahangirabad Surat,Carpet,700.0,New Property,Ready to Move,6 out of 14,Unfurnished,East,2 BHK Flat For sell IN Jahangirabad Prime Loca...,3966,2776200.0
7,Office Space for Sale in Vesu Surat,Carpet,700.0,New Property,Poss. by Sep '25,7 out of 10,1,NaN,"best commercial for business ,investors ,busin...",3392,2374400.0
...,...,...,...,...,...,...,...,...,...,...,...
4513,"4 BHK Apartment for Sale in Sangini Siddhanta,...",Super,4000.0,New Property,Ready to Move,5 out of 12,Unfurnished,East,Looking for a 4 bhk property for sale in surat...,8000,32000000.0
4514,4 BHK Apartment for Sale in Millionaires Lifes...,Super,3500.0,New Property,Poss. by Dec '26,5 out of 12,Unfurnished,East,he beautifully designed granite flooring enhan...,6500,22750000.0
4515,"4 BHK Apartment for Sale in Happy Astoria, Ves...",Super,3000.0,New Property,Poss. by Nov '28,5 out of 12,Unfurnished,East,Looking for a 4 bhk property for sale in surat...,6200,18600000.0
4516,"3 BHK Apartment for Sale in Samprati Palace, V...",Super,2620.0,Resale,Ready to Move,5 out of 12,Unfurnished,East,The beautifully designed granite flooring enha...,6031,15801220.0
4517,"4 BHK Apartment for Sale in Samprati Palace, V...",Super,3400.0,Resale,Ready to Move,5 out of 12,Unfurnished,South,Looking for a 4 bhk property for sale in surat...,6000,20400000.0

In [27]:
df['floor'].unique()

<ArrowStringArray>
[ '5 out of 10',  '6 out of 14',  '5 out of 13',  '7 out of 10',
  '3 out of 14',  '6 out of 13',   '1 out of 1',  '1 out of 13',
   '3 out of 3',   '2 out of 6',
 ...
 '16 out of 20',  '2 out of 19', '16 out of 18', '12 out of 19',
  '3 out of 19',  '3 out of 20',  '1 out of 20',  '2 out of 17',
  '9 out of 17',  '1 out of 18']
Length: 200, dtype: str

In [28]:
df['current_floor']=df['floor'].str.replace("out of ",'/').str.replace(" ","").str.split("/").str[0]
df['total_floor']=df['floor'].str.replace("out of ",'/').str.replace(" ","").str.split("/").str[1]

In [29]:
df.head(4)

,property_name,areaWithType,square_feet,transaction,status,floor,furnishing,facing,description,price_per_sqft,price,current_floor,total_floor
0,2 BHK Apartment for Sale in Dindoli Surat,Carpet,644.0,New Property,Poss. by Oct '24,5 out of 10,Unfurnished,West,"Luxury project with basement parking, Solar ro...",2891,1861804.0,5,10
1,2 BHK Apartment for Sale in Althan Surat,Super,1278.0,New Property,Poss. by Jan '26,6 out of 14,Unfurnished,South -West,2 And 3 BHK Luxurious Flat for Sell In New Alt...,3551,4538178.0,6,14
2,2 BHK Apartment for Sale in Pal Gam Surat,Super,1173.0,Resale,Ready to Move,5 out of 13,Semi-Furnished,East,This affordable 2 BHK flat is situated along a...,3800,4457400.0,5,13
3,2 BHK Apartment for Sale in Jahangirabad Surat,Carpet,700.0,New Property,Ready to Move,6 out of 14,Unfurnished,East,2 BHK Flat For sell IN Jahangirabad Prime Loca...,3966,2776200.0,6,14

In [30]:
df=df.drop(columns=['floor'])

In [31]:
df['furnishing'].unique()

<ArrowStringArray>
[            'Unfurnished',          'Semi-Furnished',
                       '1',               'Furnished',
                       nan,                       '3',
              '1 Covered,',               '2 Covered',
               '1 Covered',              '26 Covered',
                       '6',                    '> 10',
                       '2',                       '4',
                 '10 Open',              '5 Covered,',
             '50 Covered,',                  '1 Open',
              '2 Covered,', 'Vaishnodevi Ideal Homes',
             '100 Covered',                    'West',
               '5 Covered',                 '50 Open',
                 '20 Open',               '3 Covered',
                  '2 Open',             '10 Covered,']
Length: 28, dtype: str

In [32]:
valid=['Unfurnished','Semi-Furnished','Furnished']
df=df[df['furnishing'].isin(valid)]

In [33]:
df['facing'].unique()

<ArrowStringArray>
[                        'West',                  'South -West',
                         'East',                 'North - East',
                 'South - East',                    'Main Road',
                            '3',                            '2',
                            '1',                 'North - West',
 ...
         'Atithi Western Oasis',                      'Harmony',
            'Cellestial Dreams',                'Nandanvan III',
              'Samarth Enclave', 'Garden/Park, Pool, Main Road',
    'Happy Home Capital Greens',        'Shaligram The Emerald',
                        '135 X',                        '131 X']
Length: 125, dtype: str

In [34]:
valid1=['West','East','North','South','South -West','North - West','South - East','North - East']
df=df[df['facing'].isin(valid1)]

In [35]:
df.drop(columns=['description'],inplace=True)

In [36]:
df.head(4)

,property_name,areaWithType,square_feet,transaction,status,furnishing,facing,price_per_sqft,price,current_floor,total_floor
0,2 BHK Apartment for Sale in Dindoli Surat,Carpet,644.0,New Property,Poss. by Oct '24,Unfurnished,West,2891,1861804.0,5,10
1,2 BHK Apartment for Sale in Althan Surat,Super,1278.0,New Property,Poss. by Jan '26,Unfurnished,South -West,3551,4538178.0,6,14
2,2 BHK Apartment for Sale in Pal Gam Surat,Super,1173.0,Resale,Ready to Move,Semi-Furnished,East,3800,4457400.0,5,13
3,2 BHK Apartment for Sale in Jahangirabad Surat,Carpet,700.0,New Property,Ready to Move,Unfurnished,East,3966,2776200.0,6,14

In [37]:
df['BHK']=df['property_name'].str.split(" ").str[0]

In [38]:
df['area']=df['property_name'].str.split(" ").str[6]

In [39]:
df['area']

0            Dindoli
1             Althan
2                Pal
3       Jahangirabad
9           Palanpur
            ...
4513         Sangini
4514    Millionaires
4515           Happy
4516        Samprati
4517        Samprati
Name: area, Length: 2255, dtype: object

In [40]:
df=df.drop(columns=['property_name'])

In [41]:
df.sample(10)

,areaWithType,square_feet,transaction,status,furnishing,facing,price_per_sqft,price,current_floor,total_floor,BHK,area
2061,Carpet,1374.0,Resale,Ready to Move,Semi-Furnished,South,4106,5641644.0,4,5,4,Althan
2011,Carpet,1375.0,Resale,Ready to Move,Furnished,East,4509,6199875.0,11,12,2,Ratna
3426,Super,1953.0,New Property,Poss. by Apr '25,Unfurnished,South -West,5451,10645803.0,5,13,3,The
3365,Super,2246.0,New Property,Poss. by Dec '24,Unfurnished,South -West,4630,10398980.0,7,14,3,Om
4253,Carpet,2800.0,Resale,Ready to Move,Unfurnished,West,7391,20694800.0,1,2,4,in
3574,Super,2152.0,Resale,Ready to Move,Furnished,North,6738,14500176.0,3,13,3,"Swapnabhoomi,"
4506,Super,3100.0,New Property,Poss. by Jul '25,Unfurnished,South -West,6000,18600000.0,5,12,4,Universal
3797,Super,3124.0,Resale,Ready to Move,Furnished,East,9923,30999452.0,10,13,4,Celebrity
4057,Super,160.0,Resale,Ready to Move,Furnished,East,19097,3055520.0,Ground,2,5,in
3813,Carpet,2500.0,New Property,Ready to Move,Semi-Furnished,East,5020,12550000.0,8,12,6,Marion

In [42]:
df.isnull().sum()

areaWithType      0
square_feet       3
transaction       0
status            0
furnishing        0
facing            0
price_per_sqft    0
price             3
current_floor     0
total_floor       0
BHK               0
area              0
dtype: int64

In [43]:
df=df.dropna()

In [44]:
df.info()

<class 'pandas.DataFrame'>
Index: 2252 entries, 0 to 4517
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   areaWithType    2252 non-null   object
 1   square_feet     2252 non-null   float64
 2   transaction     2252 non-null   str
 3   status          2252 non-null   str
 4   furnishing      2252 non-null   str
 5   facing          2252 non-null   str
 6   price_per_sqft  2252 non-null   int64
 7   price           2252 non-null   float64
 8   current_floor   2252 non-null   object
 9   total_floor     2252 non-null   object
 10  BHK             2252 non-null   object
 11  area            2252 non-null   object
dtypes: float64(2), int64(1), object(5), str(4)
memory usage: 319.9+ KB

In [45]:
df['current_floor']=pd.to_numeric(df['current_floor'],errors='coerce')

In [46]:
df['total_floor']=df['total_floor'].astype(int)

In [47]:
df['BHK']=df['BHK'].astype(int)

In [48]:
df['furnishing'] = df['furnishing'].map({
    'Unfurnished': 1,
    'Semi-Furnished': 2,
    'Furnished': 3
})

In [49]:
df['facing'] = df['facing'].map({
    'North': 1,
    'South': 2,
    'East': 3,
    'West': 4,
    'South -West': 8,
     'North - East': 5,
     'South - East' : 7,
     'North - West': 6
    })

In [50]:
df['facing'].unique()

array([4, 8, 3, 5, 7, 6, 2, 1])

In [60]:
df.info()

<class 'pandas.DataFrame'>
Index: 2252 entries, 0 to 4517
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   areaWithType    2252 non-null   int64
 1   square_feet     2252 non-null   float64
 2   transaction     2252 non-null   int64
 3   status          2252 non-null   str
 4   furnishing      2252 non-null   int64
 5   facing          2252 non-null   int64
 6   price_per_sqft  2252 non-null   int64
 7   price           2252 non-null   float64
 8   current_floor   2141 non-null   float64
 9   total_floor     2252 non-null   int64
 10  BHK             2252 non-null   int64
 11  area            2252 non-null   object
dtypes: float64(3), int64(7), object(1), str(1)
memory usage: 260.1+ KB

In [54]:
df['areaWithType'].unique()

array([1, 2])

In [53]:
# carpet = 1, super =2
df['areaWithType']=df['areaWithType'].map({
    'Carpet' : 1,
    'Super' : 2}
                                         )

In [57]:
df['transaction'].unique()

<ArrowStringArray>
['New Property', 'Resale']
Length: 2, dtype: str

In [59]:
# new = 1 , resale=2
df['transaction']=df['transaction'].map({
    'New Property' : 1,
    'Resale' : 2}
                                       )

In [61]:
df.sample(7)

,areaWithType,square_feet,transaction,status,furnishing,facing,price_per_sqft,price,current_floor,total_floor,BHK,area
3502,2,2360.0,1,Poss. by Dec '24,1,3,5500,12980000.0,7.0,10,3,Sangini
2981,1,800.0,2,Ready to Move,1,5,4800,3840000.0,12.0,12,2,Jolly
2514,1,980.0,1,Poss. by Dec '25,1,3,4651,4557980.0,8.0,14,3,Pal
2645,2,1321.0,1,Poss. by Dec '24,1,3,5072,6700112.0,5.0,14,2,Vesu
2995,2,2578.0,1,Poss. by Jul '24,1,3,5818,14998804.0,8.0,13,3,Vesu
2365,1,1006.0,2,Poss. by Jan '25,1,3,4050,4074300.0,6.0,14,3,bhavyaraj
706,1,775.0,2,Ready to Move,1,3,3759,2913225.0,3.0,4,2,Neelkanth

In [62]:
df['square_feet']= df['square_feet'].astype(int)

In [66]:
df=df.reset_index()

In [69]:
df

,index,areaWithType,square_feet,transaction,status,furnishing,facing,price_per_sqft,price,current_floor,total_floor,BHK,area
0,0,1,644,1,Poss. by Oct '24,1,4,2891,1861804,5.0,10,2,Dindoli
1,1,2,1278,1,Poss. by Jan '26,1,8,3551,4538178,6.0,14,2,Althan
2,2,2,1173,2,Ready to Move,2,3,3800,4457400,5.0,13,2,Pal
3,3,1,700,1,Ready to Move,1,3,3966,2776200,6.0,14,2,Jahangirabad
4,9,1,720,1,Poss. by Dec '25,1,3,3200,2304000,3.0,14,2,Palanpur
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2247,4513,2,4000,1,Ready to Move,1,3,8000,32000000,5.0,12,4,Sangini
2248,4514,2,3500,1,Poss. by Dec '26,1,3,6500,22750000,5.0,12,4,Millionaires
2249,4515,2,3000,1,Poss. by Nov '28,1,3,6200,18600000,5.0,12,4,Happy
2250,4516,2,2620,2,Ready to Move,1,3,6031,15801220,5.0,12,3,Samprati
2251,4517,2,3400,2,Ready to Move,1,2,6000,20400000,5.0,12,4,Samprati

In [68]:
df['price']=df['price'].astype(int)

In [70]:
df.to_csv('proper_cleaned.csv')